<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/concept.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.ConceptCount</code>
 */
class _ConceptCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.clarifai.api.ConceptTypeCount concept_type_count = 3;</code>
     */
    private $concept_type_count = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Concept::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ConceptTypeCount concept_type_count = 3;</code>
     * @return \Clarifai\Internal\_ConceptTypeCount
     */
    public function getConceptTypeCount()
    {
        return $this->concept_type_count;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ConceptTypeCount concept_type_count = 3;</code>
     * @param \Clarifai\Internal\_ConceptTypeCount $var
     * @return $this
     */
    public function setConceptTypeCount($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_ConceptTypeCount::class);
        $this->concept_type_count = $var;

        return $this;
    }

}

