<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.ConfusionMatrix</code>
 */
class _ConfusionMatrix extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConfusionMatrixEntry matrix = 1;</code>
     */
    private $matrix;
    /**
     * Generated from protobuf field <code>repeated string concept_ids = 2;</code>
     */
    private $concept_ids;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConfusionMatrixEntry matrix = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMatrix()
    {
        return $this->matrix;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConfusionMatrixEntry matrix = 1;</code>
     * @param \Clarifai\Internal\_ConfusionMatrixEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMatrix($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_ConfusionMatrixEntry::class);
        $this->matrix = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string concept_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConceptIds()
    {
        return $this->concept_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string concept_ids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConceptIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->concept_ids = $arr;

        return $this;
    }

}

