<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Data</code>
 */
class _Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     */
    private $image = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     */
    private $video = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     */
    private $concepts;
    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     */
    private $face = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     */
    private $metadata = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     */
    private $geo = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     */
    private $colors;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     */
    private $clusters;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     */
    private $embeddings;
    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     */
    private $focus = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     */
    private $regions;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     */
    private $frames;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     * @return \Clarifai\Internal\_Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     * @param \Clarifai\Internal\_Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Image::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     * @return \Clarifai\Internal\_Video
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     * @param \Clarifai\Internal\_Video $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Video::class);
        $this->video = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConcepts()
    {
        return $this->concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     * @param \Clarifai\Internal\_Concept[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Concept::class);
        $this->concepts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     * @return \Clarifai\Internal\_Face
     */
    public function getFace()
    {
        return $this->face;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     * @param \Clarifai\Internal\_Face $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Face::class);
        $this->face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     * @return \Clarifai\Internal\_Geo
     */
    public function getGeo()
    {
        return $this->geo;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     * @param \Clarifai\Internal\_Geo $var
     * @return $this
     */
    public function setGeo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Geo::class);
        $this->geo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColors()
    {
        return $this->colors;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     * @param \Clarifai\Internal\_Color[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Color::class);
        $this->colors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClusters()
    {
        return $this->clusters;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     * @param \Clarifai\Internal\_Cluster[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClusters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Cluster::class);
        $this->clusters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmbeddings()
    {
        return $this->embeddings;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     * @param \Clarifai\Internal\_Embedding[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmbeddings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Embedding::class);
        $this->embeddings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     * @return \Clarifai\Internal\_Focus
     */
    public function getFocus()
    {
        return $this->focus;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     * @param \Clarifai\Internal\_Focus $var
     * @return $this
     */
    public function setFocus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Focus::class);
        $this->focus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegions()
    {
        return $this->regions;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     * @param \Clarifai\Internal\_Region[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Region::class);
        $this->regions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrames()
    {
        return $this->frames;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     * @param \Clarifai\Internal\_Frame[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Frame::class);
        $this->frames = $arr;

        return $this;
    }

}

