<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/vocab.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.DeleteVocabConceptsRequest</code>
 */
class _DeleteVocabConceptsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private $user_app_id = null;
    /**
     * Generated from protobuf field <code>string vocab_id = 2;</code>
     */
    private $vocab_id = '';
    /**
     * Generated from protobuf field <code>repeated string ids = 3;</code>
     */
    private $ids;
    /**
     * Generated from protobuf field <code>bool delete_all = 4;</code>
     */
    private $delete_all = false;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Vocab::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Internal\_UserAppIDSet
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Internal\_UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vocab_id = 2;</code>
     * @return string
     */
    public function getVocabId()
    {
        return $this->vocab_id;
    }

    /**
     * Generated from protobuf field <code>string vocab_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVocabId($var)
    {
        GPBUtil::checkString($var, True);
        $this->vocab_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>repeated string ids = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delete_all = 4;</code>
     * @return bool
     */
    public function getDeleteAll()
    {
        return $this->delete_all;
    }

    /**
     * Generated from protobuf field <code>bool delete_all = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteAll($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_all = $var;

        return $this;
    }

}

