<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/embedding.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Embedding</code>
 */
class _Embedding extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated float vector = 1 [packed = true];</code>
     */
    private $vector;
    /**
     * Generated from protobuf field <code>uint32 num_dimensions = 2;</code>
     */
    private $num_dimensions = 0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Embedding::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated float vector = 1 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVector()
    {
        return $this->vector;
    }

    /**
     * Generated from protobuf field <code>repeated float vector = 1 [packed = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVector($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->vector = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 num_dimensions = 2;</code>
     * @return int
     */
    public function getNumDimensions()
    {
        return $this->num_dimensions;
    }

    /**
     * Generated from protobuf field <code>uint32 num_dimensions = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumDimensions($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_dimensions = $var;

        return $this;
    }

}

