<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.EvalTestSetEntry</code>
 */
class _EvalTestSetEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string url = 2;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     */
    private $predicted_concepts;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     */
    private $ground_truth_concepts;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPredictedConcepts()
    {
        return $this->predicted_concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept predicted_concepts = 3;</code>
     * @param \Clarifai\Internal\_Concept[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPredictedConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Concept::class);
        $this->predicted_concepts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroundTruthConcepts()
    {
        return $this->ground_truth_concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept ground_truth_concepts = 4;</code>
     * @param \Clarifai\Internal\_Concept[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroundTruthConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Concept::class);
        $this->ground_truth_concepts = $arr;

        return $this;
    }

}

