<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/focus.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Focus</code>
 */
class _Focus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $density = 0.0;
    /**
     * Generated from protobuf field <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $value = 0.0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Focus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return float
     */
    public function getDensity()
    {
        return $this->density;
    }

    /**
     * Generated from protobuf field <code>float density = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float $var
     * @return $this
     */
    public function setDensity($var)
    {
        GPBUtil::checkFloat($var);
        $this->density = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>float value = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

}

