<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Frame</code>
 */
class _Frame extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.FrameInfo frame_info = 1;</code>
     */
    private $frame_info = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     */
    private $data = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FrameInfo frame_info = 1;</code>
     * @return \Clarifai\Internal\_FrameInfo
     */
    public function getFrameInfo()
    {
        return $this->frame_info;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FrameInfo frame_info = 1;</code>
     * @param \Clarifai\Internal\_FrameInfo $var
     * @return $this
     */
    public function setFrameInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_FrameInfo::class);
        $this->frame_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     * @return \Clarifai\Internal\_Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 2;</code>
     * @param \Clarifai\Internal\_Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Data::class);
        $this->data = $var;

        return $this;
    }

}

