<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.GetModelVersionMetricsRequest.FieldsValue</code>
 */
class _GetModelVersionMetricsRequest_FieldsValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool confusion_matrix = 1;</code>
     */
    private $confusion_matrix = false;
    /**
     * Generated from protobuf field <code>bool cooccurrence_matrix = 2;</code>
     */
    private $cooccurrence_matrix = false;
    /**
     * Generated from protobuf field <code>bool label_counts = 3;</code>
     */
    private $label_counts = false;
    /**
     * Generated from protobuf field <code>bool binary_metrics = 4;</code>
     */
    private $binary_metrics = false;
    /**
     * Generated from protobuf field <code>bool test_set = 5;</code>
     */
    private $test_set = false;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool confusion_matrix = 1;</code>
     * @return bool
     */
    public function getConfusionMatrix()
    {
        return $this->confusion_matrix;
    }

    /**
     * Generated from protobuf field <code>bool confusion_matrix = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setConfusionMatrix($var)
    {
        GPBUtil::checkBool($var);
        $this->confusion_matrix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool cooccurrence_matrix = 2;</code>
     * @return bool
     */
    public function getCooccurrenceMatrix()
    {
        return $this->cooccurrence_matrix;
    }

    /**
     * Generated from protobuf field <code>bool cooccurrence_matrix = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCooccurrenceMatrix($var)
    {
        GPBUtil::checkBool($var);
        $this->cooccurrence_matrix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool label_counts = 3;</code>
     * @return bool
     */
    public function getLabelCounts()
    {
        return $this->label_counts;
    }

    /**
     * Generated from protobuf field <code>bool label_counts = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setLabelCounts($var)
    {
        GPBUtil::checkBool($var);
        $this->label_counts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool binary_metrics = 4;</code>
     * @return bool
     */
    public function getBinaryMetrics()
    {
        return $this->binary_metrics;
    }

    /**
     * Generated from protobuf field <code>bool binary_metrics = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBinaryMetrics($var)
    {
        GPBUtil::checkBool($var);
        $this->binary_metrics = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool test_set = 5;</code>
     * @return bool
     */
    public function getTestSet()
    {
        return $this->test_set;
    }

    /**
     * Generated from protobuf field <code>bool test_set = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setTestSet($var)
    {
        GPBUtil::checkBool($var);
        $this->test_set = $var;

        return $this;
    }

}

