<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/subscription.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.GetSubscriptionRequest</code>
 */
class _GetSubscriptionRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Subscription::initOnce();
        parent::__construct();
    }

}

