<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/input.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.InputCount</code>
 */
class _InputCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 processed = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $processed = 0;
    /**
     * Generated from protobuf field <code>uint32 to_process = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $to_process = 0;
    /**
     * Generated from protobuf field <code>uint32 errors = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $errors = 0;
    /**
     * Generated from protobuf field <code>uint32 processing = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $processing = 0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Input::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 processed = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getProcessed()
    {
        return $this->processed;
    }

    /**
     * Generated from protobuf field <code>uint32 processed = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setProcessed($var)
    {
        GPBUtil::checkUint32($var);
        $this->processed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 to_process = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getToProcess()
    {
        return $this->to_process;
    }

    /**
     * Generated from protobuf field <code>uint32 to_process = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setToProcess($var)
    {
        GPBUtil::checkUint32($var);
        $this->to_process = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 errors = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>uint32 errors = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setErrors($var)
    {
        GPBUtil::checkUint32($var);
        $this->errors = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 processing = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getProcessing()
    {
        return $this->processing;
    }

    /**
     * Generated from protobuf field <code>uint32 processing = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setProcessing($var)
    {
        GPBUtil::checkUint32($var);
        $this->processing = $var;

        return $this;
    }

}

