<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.LabelDistribution</code>
 */
class _LabelDistribution extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.LabelCount positive_label_counts = 1;</code>
     */
    private $positive_label_counts;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.LabelCount positive_label_counts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPositiveLabelCounts()
    {
        return $this->positive_label_counts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.LabelCount positive_label_counts = 1;</code>
     * @param \Clarifai\Internal\_LabelCount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPositiveLabelCounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_LabelCount::class);
        $this->positive_label_counts = $arr;

        return $this;
    }

}

