<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.LabelCount</code>
 */
class _LabelCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string concept_name = 1;</code>
     */
    private $concept_name = '';
    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string concept_name = 1;</code>
     * @return string
     */
    public function getConceptName()
    {
        return $this->concept_name;
    }

    /**
     * Generated from protobuf field <code>string concept_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConceptName($var)
    {
        GPBUtil::checkString($var, True);
        $this->concept_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

