<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Mask</code>
 */
class _Mask extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.Color color = 1;</code>
     */
    private $color = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 2;</code>
     */
    private $image = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Color color = 1;</code>
     * @return \Clarifai\Internal\_Color
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Color color = 1;</code>
     * @param \Clarifai\Internal\_Color $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Color::class);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 2;</code>
     * @return \Clarifai\Internal\_Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 2;</code>
     * @param \Clarifai\Internal\_Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Image::class);
        $this->image = $var;

        return $this;
    }

}

