<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Model</code>
 */
class _Model extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    private $created_at = null;
    /**
     * Generated from protobuf field <code>string app_id = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $app_id = '';
    /**
     * Generated from protobuf field <code>.clarifai.api.OutputInfo output_info = 5;</code>
     */
    private $output_info = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 6;</code>
     */
    private $model_version = null;
    /**
     * Generated from protobuf field <code>string display_name = 7;</code>
     */
    private $display_name = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Model::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_id = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>string app_id = 4 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.OutputInfo output_info = 5;</code>
     * @return \Clarifai\Internal\_OutputInfo
     */
    public function getOutputInfo()
    {
        return $this->output_info;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.OutputInfo output_info = 5;</code>
     * @param \Clarifai\Internal\_OutputInfo $var
     * @return $this
     */
    public function setOutputInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_OutputInfo::class);
        $this->output_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 6;</code>
     * @return \Clarifai\Internal\_ModelVersion
     */
    public function getModelVersion()
    {
        return $this->model_version;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 6;</code>
     * @param \Clarifai\Internal\_ModelVersion $var
     * @return $this
     */
    public function setModelVersion($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_ModelVersion::class);
        $this->model_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 7;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

}

