<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.OutputConfig</code>
 */
class _OutputConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool concepts_mutually_exclusive = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $concepts_mutually_exclusive = false;
    /**
     * Generated from protobuf field <code>bool closed_environment = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $closed_environment = false;
    /**
     * Generated from protobuf field <code>string existing_model_id = 3 [deprecated = true];</code>
     */
    private $existing_model_id = '';
    /**
     * Generated from protobuf field <code>string language = 4;</code>
     */
    private $language = '';
    /**
     * Generated from protobuf field <code>string hyper_parameters = 5;</code>
     */
    private $hyper_parameters = '';
    /**
     * Generated from protobuf field <code>uint32 max_concepts = 6 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $max_concepts = 0;
    /**
     * Generated from protobuf field <code>float min_value = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $min_value = 0.0;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept select_concepts = 8;</code>
     */
    private $select_concepts;
    /**
     * Generated from protobuf field <code>uint32 training_timeout = 9;</code>
     */
    private $training_timeout = 0;
    /**
     * Generated from protobuf field <code>uint32 sample_ms = 10;</code>
     */
    private $sample_ms = 0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Model::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool concepts_mutually_exclusive = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return bool
     */
    public function getConceptsMutuallyExclusive()
    {
        return $this->concepts_mutually_exclusive;
    }

    /**
     * Generated from protobuf field <code>bool concepts_mutually_exclusive = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setConceptsMutuallyExclusive($var)
    {
        GPBUtil::checkBool($var);
        $this->concepts_mutually_exclusive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool closed_environment = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return bool
     */
    public function getClosedEnvironment()
    {
        return $this->closed_environment;
    }

    /**
     * Generated from protobuf field <code>bool closed_environment = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param bool $var
     * @return $this
     */
    public function setClosedEnvironment($var)
    {
        GPBUtil::checkBool($var);
        $this->closed_environment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string existing_model_id = 3 [deprecated = true];</code>
     * @return string
     */
    public function getExistingModelId()
    {
        return $this->existing_model_id;
    }

    /**
     * Generated from protobuf field <code>string existing_model_id = 3 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setExistingModelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->existing_model_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 4;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hyper_parameters = 5;</code>
     * @return string
     */
    public function getHyperParameters()
    {
        return $this->hyper_parameters;
    }

    /**
     * Generated from protobuf field <code>string hyper_parameters = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHyperParameters($var)
    {
        GPBUtil::checkString($var, True);
        $this->hyper_parameters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_concepts = 6 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return int
     */
    public function getMaxConcepts()
    {
        return $this->max_concepts;
    }

    /**
     * Generated from protobuf field <code>uint32 max_concepts = 6 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConcepts($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_concepts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float min_value = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return float
     */
    public function getMinValue()
    {
        return $this->min_value;
    }

    /**
     * Generated from protobuf field <code>float min_value = 7 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float $var
     * @return $this
     */
    public function setMinValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept select_concepts = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSelectConcepts()
    {
        return $this->select_concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept select_concepts = 8;</code>
     * @param \Clarifai\Internal\_Concept[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSelectConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Concept::class);
        $this->select_concepts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 training_timeout = 9;</code>
     * @return int
     */
    public function getTrainingTimeout()
    {
        return $this->training_timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 training_timeout = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTrainingTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->training_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_ms = 10;</code>
     * @return int
     */
    public function getSampleMs()
    {
        return $this->sample_ms;
    }

    /**
     * Generated from protobuf field <code>uint32 sample_ms = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSampleMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->sample_ms = $var;

        return $this;
    }

}

