<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.OutputInfo</code>
 */
class _OutputInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 1;</code>
     */
    private $data = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.OutputConfig output_config = 2;</code>
     */
    private $output_config = null;
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string type = 4;</code>
     */
    private $type = '';
    /**
     * Generated from protobuf field <code>string type_ext = 5;</code>
     */
    private $type_ext = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Model::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 1;</code>
     * @return \Clarifai\Internal\_Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 1;</code>
     * @param \Clarifai\Internal\_Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Data::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.OutputConfig output_config = 2;</code>
     * @return \Clarifai\Internal\_OutputConfig
     */
    public function getOutputConfig()
    {
        return $this->output_config;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.OutputConfig output_config = 2;</code>
     * @param \Clarifai\Internal\_OutputConfig $var
     * @return $this
     */
    public function setOutputConfig($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_OutputConfig::class);
        $this->output_config = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type_ext = 5;</code>
     * @return string
     */
    public function getTypeExt()
    {
        return $this->type_ext;
    }

    /**
     * Generated from protobuf field <code>string type_ext = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeExt($var)
    {
        GPBUtil::checkString($var, True);
        $this->type_ext = $var;

        return $this;
    }

}

