<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/concept_language.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PatchConceptLanguagesRequest</code>
 */
class _PatchConceptLanguagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private $user_app_id = null;
    /**
     * Generated from protobuf field <code>string concept_id = 2;</code>
     */
    private $concept_id = '';
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConceptLanguage concept_languages = 3;</code>
     */
    private $concept_languages;
    /**
     * Generated from protobuf field <code>string action = 4;</code>
     */
    private $action = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ConceptLanguage::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Internal\_UserAppIDSet
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Internal\_UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string concept_id = 2;</code>
     * @return string
     */
    public function getConceptId()
    {
        return $this->concept_id;
    }

    /**
     * Generated from protobuf field <code>string concept_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConceptId($var)
    {
        GPBUtil::checkString($var, True);
        $this->concept_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConceptLanguage concept_languages = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConceptLanguages()
    {
        return $this->concept_languages;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.ConceptLanguage concept_languages = 3;</code>
     * @param \Clarifai\Internal\_ConceptLanguage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConceptLanguages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_ConceptLanguage::class);
        $this->concept_languages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

}

