<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/vocab.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PatchVocabsRequest</code>
 */
class _PatchVocabsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private $user_app_id = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Vocab vocabs = 2;</code>
     */
    private $vocabs;
    /**
     * Generated from protobuf field <code>string action = 3;</code>
     */
    private $action = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Vocab::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Internal\_UserAppIDSet
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Internal\_UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Vocab vocabs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVocabs()
    {
        return $this->vocabs;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Vocab vocabs = 2;</code>
     * @param \Clarifai\Internal\_Vocab[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVocabs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Vocab::class);
        $this->vocabs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 3;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

}

