<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/workflow.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PostWorkflowResultsResponse</code>
 */
class _PostWorkflowResultsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Workflow workflow = 2;</code>
     */
    private $workflow = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.WorkflowResult results = 3;</code>
     */
    private $results;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Workflow::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Internal\Status\_Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Internal\Status\_Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\Status\_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Workflow workflow = 2;</code>
     * @return \Clarifai\Internal\_Workflow
     */
    public function getWorkflow()
    {
        return $this->workflow;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Workflow workflow = 2;</code>
     * @param \Clarifai\Internal\_Workflow $var
     * @return $this
     */
    public function setWorkflow($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Workflow::class);
        $this->workflow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.WorkflowResult results = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.WorkflowResult results = 3;</code>
     * @param \Clarifai\Internal\_WorkflowResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_WorkflowResult::class);
        $this->results = $arr;

        return $this;
    }

}

