<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PostModelsRequest</code>
 */
class _PostModelsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private $user_app_id = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Model model = 2 [deprecated = true];</code>
     */
    private $model = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Model models = 3;</code>
     */
    private $models;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Model::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return \Clarifai\Internal\_UserAppIDSet
     */
    public function getUserAppId()
    {
        return $this->user_app_id;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @param \Clarifai\Internal\_UserAppIDSet $var
     * @return $this
     */
    public function setUserAppId($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_UserAppIDSet::class);
        $this->user_app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Model model = 2 [deprecated = true];</code>
     * @return \Clarifai\Internal\_Model
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Model model = 2 [deprecated = true];</code>
     * @param \Clarifai\Internal\_Model $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Model::class);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Model models = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModels()
    {
        return $this->models;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Model models = 3;</code>
     * @param \Clarifai\Internal\_Model[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Internal\_Model::class);
        $this->models = $arr;

        return $this;
    }

}

