<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.RegionInfo</code>
 */
class _RegionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.BoundingBox bounding_box = 1;</code>
     */
    private $bounding_box = null;
    /**
     * Generated from protobuf field <code>float value = 2;</code>
     */
    private $value = 0.0;
    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfoFeedback feedback = 3;</code>
     */
    private $feedback = 0;
    /**
     * Generated from protobuf field <code>.clarifai.api.Mask mask = 4;</code>
     */
    private $mask = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.BoundingBox bounding_box = 1;</code>
     * @return \Clarifai\Internal\_BoundingBox
     */
    public function getBoundingBox()
    {
        return $this->bounding_box;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.BoundingBox bounding_box = 1;</code>
     * @param \Clarifai\Internal\_BoundingBox $var
     * @return $this
     */
    public function setBoundingBox($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_BoundingBox::class);
        $this->bounding_box = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>float value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfoFeedback feedback = 3;</code>
     * @return int
     */
    public function getFeedback()
    {
        return $this->feedback;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfoFeedback feedback = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFeedback($var)
    {
        GPBUtil::checkEnum($var, \Clarifai\Internal\_RegionInfoFeedback::class);
        $this->feedback = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Mask mask = 4;</code>
     * @return \Clarifai\Internal\_Mask
     */
    public function getMask()
    {
        return $this->mask;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Mask mask = 4;</code>
     * @param \Clarifai\Internal\_Mask $var
     * @return $this
     */
    public function setMask($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Internal\_Mask::class);
        $this->mask = $var;

        return $this;
    }

}

