<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Internal;

/**
 * Protobuf enum <code>Clarifai\Api\RegionInfoFeedback</code>
 */
class _RegionInfoFeedback
{
    /**
     * Generated from protobuf enum <code>accurate = 0;</code>
     */
    const accurate = 0;
    /**
     * Generated from protobuf enum <code>misplaced = 1;</code>
     */
    const misplaced = 1;
    /**
     * Generated from protobuf enum <code>not_detected = 2;</code>
     */
    const not_detected = 2;
    /**
     * Generated from protobuf enum <code>false_positive = 3;</code>
     */
    const false_positive = 3;
}

