<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.ROC</code>
 */
class _ROC extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated float fpr = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $fpr;
    /**
     * Generated from protobuf field <code>repeated float tpr = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $tpr;
    /**
     * Generated from protobuf field <code>repeated float thresholds = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     */
    private $thresholds;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated float fpr = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFpr()
    {
        return $this->fpr;
    }

    /**
     * Generated from protobuf field <code>repeated float fpr = 1 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFpr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->fpr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float tpr = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTpr()
    {
        return $this->tpr;
    }

    /**
     * Generated from protobuf field <code>repeated float tpr = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTpr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->tpr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float thresholds = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThresholds()
    {
        return $this->thresholds;
    }

    /**
     * Generated from protobuf field <code>repeated float thresholds = 3 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThresholds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->thresholds = $arr;

        return $this;
    }

}

