<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/text.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Text</code>
 */
class _Text extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     */
    private $raw = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Text::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     * @return string
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRaw($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw = $var;

        return $this;
    }

}

