<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/usage_interval_type.proto

namespace Clarifai\Internal;

/**
 * Protobuf enum <code>Clarifai\Api\UsageIntervalType</code>
 */
class _UsageIntervalType
{
    /**
     * Generated from protobuf enum <code>undef = 0;</code>
     */
    const undef = 0;
    /**
     * Generated from protobuf enum <code>day = 1;</code>
     */
    const day = 1;
    /**
     * Generated from protobuf enum <code>month = 2;</code>
     */
    const month = 2;
    /**
     * Generated from protobuf enum <code>year = 3;</code>
     */
    const year = 3;
}

