<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/color.proto

namespace Clarifai\Internal;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.W3C</code>
 */
class _W3C extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hex = 1;</code>
     */
    private $hex = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Color::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string hex = 1;</code>
     * @return string
     */
    public function getHex()
    {
        return $this->hex;
    }

    /**
     * Generated from protobuf field <code>string hex = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHex($var)
    {
        GPBUtil::checkString($var, True);
        $this->hex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

