build: off
shallow_clone: false
platform:
  - x64
clone_folder: C:\projects\private-clarifai-php

environment:
  matrix:
    - dependencies: current
      php_ver_target: 7.0.33
    - dependencies: current
      php_ver_target: 7.1.26
    - dependencies: current
      php_ver_target: 7.2.15

cache:
  - '%LOCALAPPDATA%\Composer'
  - '%LOCALAPPDATA%\Temp\Chocolatey'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)
  - refreshenv

install:
  # Enable Windows Update service, needed to install vcredist2015 (dependency of php)
  - ps: Set-Service wuauserv -StartupType Manual
  - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
  - choco install -y php --version %php_ver_target% --params '"/InstallDir:C:\tools\php"'
  - choco install -y composer
  - refreshenv
  - composer install --no-interaction --no-progress --prefer-dist
  - cd C:\tools\php
  - echo extension=php_curl.dll >> php.ini

test_script:
  - cd C:\projects\private-clarifai-php
  - vendor/bin/phpunit -c phpunit.xml -v
