build: off
shallow_clone: false
platform:
  - x64
clone_folder: C:\projects\private-clarifai-php

environment:
  matrix:
    - PHP_VERSION: 7.0.33
    - PHP_VERSION: 7.1.26
    - PHP_VERSION: 7.2.15
    - PHP_VERSION: 7.3.1

cache:
  - '%LOCALAPPDATA%\Composer'
  - '%LOCALAPPDATA%\Temp\Chocolatey'

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)
  - refreshenv

install:
  # Enable Windows Update service, needed to install vcredist2015 (dependency of php)
  - ps: Set-Service wuauserv -StartupType Manual
  - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
  - choco install -y php --version %PHP_VERSION% --params '"/InstallDir:C:\tools\php"'
  - choco install -y composer
  - refreshenv
  - composer install --no-interaction --no-progress --prefer-dist
  - cd C:\tools\php
  - echo extension=php_curl.dll >> php.ini

before_test:
  - cd C:\projects\private-clarifai-php
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-app php-appveyor') do set CLARIFAI_APP_ID=%%i
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-key %CLARIFAI_APP_ID%') do set CLARIFAI_API_KEY=%%i
  - for /f %%i in ('C:\Python36\python.exe scripts\app_and_key_for_tests.py --create-workflow %CLARIFAI_API_KEY%') do rem

test_script:
  - cd C:\projects\private-clarifai-php
  - vendor/bin/phpunit -c phpunit.xml -v

after_test:
  - cd C:\projects\private-clarifai-php
  - 'C:\Python36\python.exe scripts\app_and_key_for_tests.py --delete-app %CLARIFAI_APP_ID%'
