<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     */
    private $image = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     */
    private $video = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     */
    private $concepts;
    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     */
    private $face = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     */
    private $metadata = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     */
    private $geo = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     */
    private $colors;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     */
    private $clusters;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     */
    private $embeddings;
    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     */
    private $focus = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     */
    private $regions;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     */
    private $frames;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     * @return \Clarifai\Grpc\Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Image image = 1;</code>
     * @param \Clarifai\Grpc\Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Image::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     * @return \Clarifai\Grpc\Video
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Video video = 2;</code>
     * @param \Clarifai\Grpc\Video $var
     * @return $this
     */
    public function setVideo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Video::class);
        $this->video = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConcepts()
    {
        return $this->concepts;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Concept concepts = 3;</code>
     * @param \Clarifai\Grpc\Concept[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConcepts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Concept::class);
        $this->concepts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     * @return \Clarifai\Grpc\Face
     */
    public function getFace()
    {
        return $this->face;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Face face = 4;</code>
     * @param \Clarifai\Grpc\Face $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Face::class);
        $this->face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     * @return \Google\Protobuf\Struct
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 5;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     * @return \Clarifai\Grpc\Geo
     */
    public function getGeo()
    {
        return $this->geo;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Geo geo = 6;</code>
     * @param \Clarifai\Grpc\Geo $var
     * @return $this
     */
    public function setGeo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Geo::class);
        $this->geo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColors()
    {
        return $this->colors;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Color colors = 7;</code>
     * @param \Clarifai\Grpc\Color[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Color::class);
        $this->colors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClusters()
    {
        return $this->clusters;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Cluster clusters = 8;</code>
     * @param \Clarifai\Grpc\Cluster[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClusters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Cluster::class);
        $this->clusters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmbeddings()
    {
        return $this->embeddings;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Embedding embeddings = 9;</code>
     * @param \Clarifai\Grpc\Embedding[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmbeddings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Embedding::class);
        $this->embeddings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     * @return \Clarifai\Grpc\Focus
     */
    public function getFocus()
    {
        return $this->focus;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Focus focus = 10;</code>
     * @param \Clarifai\Grpc\Focus $var
     * @return $this
     */
    public function setFocus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Focus::class);
        $this->focus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegions()
    {
        return $this->regions;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Region regions = 11;</code>
     * @param \Clarifai\Grpc\Region[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Region::class);
        $this->regions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrames()
    {
        return $this->frames;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.Frame frames = 12;</code>
     * @param \Clarifai\Grpc\Frame[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\Frame::class);
        $this->frames = $arr;

        return $this;
    }

}

