<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.EvalMetrics</code>
 */
class EvalMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.MetricsSummary summary = 2;</code>
     */
    private $summary = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.ConfusionMatrix confusion_matrix = 3;</code>
     */
    private $confusion_matrix = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.CooccurrenceMatrix cooccurrence_matrix = 4;</code>
     */
    private $cooccurrence_matrix = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.LabelDistribution label_counts = 5;</code>
     */
    private $label_counts = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.BinaryMetrics binary_metrics = 6;</code>
     */
    private $binary_metrics;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.EvalTestSetEntry test_set = 7;</code>
     */
    private $test_set;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Grpc\Status\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Grpc\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.MetricsSummary summary = 2;</code>
     * @return \Clarifai\Grpc\MetricsSummary
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.MetricsSummary summary = 2;</code>
     * @param \Clarifai\Grpc\MetricsSummary $var
     * @return $this
     */
    public function setSummary($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\MetricsSummary::class);
        $this->summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ConfusionMatrix confusion_matrix = 3;</code>
     * @return \Clarifai\Grpc\ConfusionMatrix
     */
    public function getConfusionMatrix()
    {
        return $this->confusion_matrix;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ConfusionMatrix confusion_matrix = 3;</code>
     * @param \Clarifai\Grpc\ConfusionMatrix $var
     * @return $this
     */
    public function setConfusionMatrix($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\ConfusionMatrix::class);
        $this->confusion_matrix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.CooccurrenceMatrix cooccurrence_matrix = 4;</code>
     * @return \Clarifai\Grpc\CooccurrenceMatrix
     */
    public function getCooccurrenceMatrix()
    {
        return $this->cooccurrence_matrix;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.CooccurrenceMatrix cooccurrence_matrix = 4;</code>
     * @param \Clarifai\Grpc\CooccurrenceMatrix $var
     * @return $this
     */
    public function setCooccurrenceMatrix($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\CooccurrenceMatrix::class);
        $this->cooccurrence_matrix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.LabelDistribution label_counts = 5;</code>
     * @return \Clarifai\Grpc\LabelDistribution
     */
    public function getLabelCounts()
    {
        return $this->label_counts;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.LabelDistribution label_counts = 5;</code>
     * @param \Clarifai\Grpc\LabelDistribution $var
     * @return $this
     */
    public function setLabelCounts($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\LabelDistribution::class);
        $this->label_counts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.BinaryMetrics binary_metrics = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBinaryMetrics()
    {
        return $this->binary_metrics;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.BinaryMetrics binary_metrics = 6;</code>
     * @param \Clarifai\Grpc\BinaryMetrics[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBinaryMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\BinaryMetrics::class);
        $this->binary_metrics = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.EvalTestSetEntry test_set = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTestSet()
    {
        return $this->test_set;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.EvalTestSetEntry test_set = 7;</code>
     * @param \Clarifai\Grpc\EvalTestSetEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTestSet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\EvalTestSetEntry::class);
        $this->test_set = $arr;

        return $this;
    }

}

