<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/feedback.proto

namespace Clarifai\Grpc;

/**
 * Protobuf enum <code>Clarifai\Api\EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>undefined = 0;</code>
     */
    const undefined = 0;
    /**
     * Generated from protobuf enum <code>search_click = 1;</code>
     */
    const search_click = 1;
    /**
     * Generated from protobuf enum <code>annotation = 2;</code>
     */
    const annotation = 2;
}

