<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/face.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Face</code>
 */
class Face extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.FaceIdentity identity = 1;</code>
     */
    private $identity = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.FaceAge age_appearance = 2;</code>
     */
    private $age_appearance = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.FaceGenderIdentity gender_appearance = 3;</code>
     */
    private $gender_appearance = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.FaceMCAffinity multicultural_appearance = 4;</code>
     */
    private $multicultural_appearance = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Face::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceIdentity identity = 1;</code>
     * @return \Clarifai\Grpc\FaceIdentity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceIdentity identity = 1;</code>
     * @param \Clarifai\Grpc\FaceIdentity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\FaceIdentity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceAge age_appearance = 2;</code>
     * @return \Clarifai\Grpc\FaceAge
     */
    public function getAgeAppearance()
    {
        return $this->age_appearance;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceAge age_appearance = 2;</code>
     * @param \Clarifai\Grpc\FaceAge $var
     * @return $this
     */
    public function setAgeAppearance($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\FaceAge::class);
        $this->age_appearance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceGenderIdentity gender_appearance = 3;</code>
     * @return \Clarifai\Grpc\FaceGenderIdentity
     */
    public function getGenderAppearance()
    {
        return $this->gender_appearance;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceGenderIdentity gender_appearance = 3;</code>
     * @param \Clarifai\Grpc\FaceGenderIdentity $var
     * @return $this
     */
    public function setGenderAppearance($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\FaceGenderIdentity::class);
        $this->gender_appearance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceMCAffinity multicultural_appearance = 4;</code>
     * @return \Clarifai\Grpc\FaceMCAffinity
     */
    public function getMulticulturalAppearance()
    {
        return $this->multicultural_appearance;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.FaceMCAffinity multicultural_appearance = 4;</code>
     * @param \Clarifai\Grpc\FaceMCAffinity $var
     * @return $this
     */
    public function setMulticulturalAppearance($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\FaceMCAffinity::class);
        $this->multicultural_appearance = $var;

        return $this;
    }

}

