<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/geo.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Geo</code>
 */
class Geo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     */
    private $geo_point = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.GeoLimit geo_limit = 2;</code>
     */
    private $geo_limit = null;
    /**
     * Generated from protobuf field <code>repeated .clarifai.api.GeoBoxedPoint geo_box = 3;</code>
     */
    private $geo_box;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Geo::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     * @return \Clarifai\Grpc\GeoPoint
     */
    public function getGeoPoint()
    {
        return $this->geo_point;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     * @param \Clarifai\Grpc\GeoPoint $var
     * @return $this
     */
    public function setGeoPoint($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\GeoPoint::class);
        $this->geo_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoLimit geo_limit = 2;</code>
     * @return \Clarifai\Grpc\GeoLimit
     */
    public function getGeoLimit()
    {
        return $this->geo_limit;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoLimit geo_limit = 2;</code>
     * @param \Clarifai\Grpc\GeoLimit $var
     * @return $this
     */
    public function setGeoLimit($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\GeoLimit::class);
        $this->geo_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.GeoBoxedPoint geo_box = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeoBox()
    {
        return $this->geo_box;
    }

    /**
     * Generated from protobuf field <code>repeated .clarifai.api.GeoBoxedPoint geo_box = 3;</code>
     * @param \Clarifai\Grpc\GeoBoxedPoint[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeoBox($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Clarifai\Grpc\GeoBoxedPoint::class);
        $this->geo_box = $arr;

        return $this;
    }

}

