<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/geo.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.GeoBoxedPoint</code>
 */
class GeoBoxedPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     */
    private $geo_point = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Geo::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     * @return \Clarifai\Grpc\GeoPoint
     */
    public function getGeoPoint()
    {
        return $this->geo_point;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.GeoPoint geo_point = 1;</code>
     * @param \Clarifai\Grpc\GeoPoint $var
     * @return $this
     */
    public function setGeoPoint($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\GeoPoint::class);
        $this->geo_point = $var;

        return $this;
    }

}

