<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/search.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Hit</code>
 */
class Hit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float score = 1;</code>
     */
    private $score = 0.0;
    /**
     * Generated from protobuf field <code>.clarifai.api.Input input = 2;</code>
     */
    private $input = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Search::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>float score = 1;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>float score = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Input input = 2;</code>
     * @return \Clarifai\Grpc\Input
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Input input = 2;</code>
     * @param \Clarifai\Grpc\Input $var
     * @return $this
     */
    public function setInput($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Input::class);
        $this->input = $var;

        return $this;
    }

}

