<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/subscription.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.PostSubscriptionRequest</code>
 */
class PostSubscriptionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     */
    private $signup_code = '';
    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     */
    private $plan = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Subscription::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     * @return string
     */
    public function getSignupCode()
    {
        return $this->signup_code;
    }

    /**
     * Generated from protobuf field <code>string signup_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignupCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->signup_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     * @return \Clarifai\Grpc\Plan
     */
    public function getPlan()
    {
        return $this->plan;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Plan plan = 2;</code>
     * @param \Clarifai\Grpc\Plan $var
     * @return $this
     */
    public function setPlan($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Plan::class);
        $this->plan = $var;

        return $this;
    }

}

