<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/data.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.Region</code>
 */
class Region extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     */
    private $region_info = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     */
    private $data = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     * @return \Clarifai\Grpc\RegionInfo
     */
    public function getRegionInfo()
    {
        return $this->region_info;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.RegionInfo region_info = 2;</code>
     * @param \Clarifai\Grpc\RegionInfo $var
     * @return $this
     */
    public function setRegionInfo($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\RegionInfo::class);
        $this->region_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     * @return \Clarifai\Grpc\Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Data data = 3;</code>
     * @param \Clarifai\Grpc\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Data::class);
        $this->data = $var;

        return $this;
    }

}

