<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/model_version.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.SingleModelVersionResponse</code>
 */
class SingleModelVersionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 2;</code>
     */
    private $model_version = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\ModelVersion::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Grpc\Status\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Grpc\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 2;</code>
     * @return \Clarifai\Grpc\ModelVersion
     */
    public function getModelVersion()
    {
        return $this->model_version;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.ModelVersion model_version = 2;</code>
     * @param \Clarifai\Grpc\ModelVersion $var
     * @return $this
     */
    public function setModelVersion($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\ModelVersion::class);
        $this->model_version = $var;

        return $this;
    }

}

