<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/vocab.proto

namespace Clarifai\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>clarifai.api.SingleVocabResponse</code>
 */
class SingleVocabResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     */
    private $status = null;
    /**
     * Generated from protobuf field <code>.clarifai.api.Vocab vocab = 2;</code>
     */
    private $vocab = null;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Api\Vocab::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @return \Clarifai\Grpc\Status\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.status.Status status = 1;</code>
     * @param \Clarifai\Grpc\Status\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Status\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Vocab vocab = 2;</code>
     * @return \Clarifai\Grpc\Vocab
     */
    public function getVocab()
    {
        return $this->vocab;
    }

    /**
     * Generated from protobuf field <code>.clarifai.api.Vocab vocab = 2;</code>
     * @param \Clarifai\Grpc\Vocab $var
     * @return $this
     */
    public function setVocab($var)
    {
        GPBUtil::checkMessage($var, \Clarifai\Grpc\Vocab::class);
        $this->vocab = $var;

        return $this;
    }

}

