<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/cluster.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Cluster
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a750a2070726f746f2f636c6172696661692f6170692f636c7573746572" .
            "2e70726f746f120c636c6172696661692e61706922150a07436c75737465" .
            "72120a0a02696418012001280942245a03617069a2020443414950c20201" .
            "5fca0211436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

