<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/code.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Code
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Status\Status::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5020a1d70726f746f2f636c6172696661692f6170692f636f64652e70" .
            "726f746f120c636c6172696661692e617069222e0a144765745374617475" .
            "73436f64655265717565737412160a0e7374617475735f636f64655f6964" .
            "18012001280922180a164c697374537461747573436f6465735265717565" .
            "737422470a1853696e676c65537461747573436f6465526573706f6e7365" .
            "122b0a0673746174757318012001280b321b2e636c6172696661692e6170" .
            "692e7374617475732e53746174757322750a174d756c7469537461747573" .
            "436f6465526573706f6e7365122b0a0673746174757318012001280b321b" .
            "2e636c6172696661692e6170692e7374617475732e537461747573122d0a" .
            "08737461747573657318022003280b321b2e636c6172696661692e617069" .
            "2e7374617475732e53746174757342245a03617069a2020443414950c202" .
            "015fca0211436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

