<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/color.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Color
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac7010a1e70726f746f2f636c6172696661692f6170692f636f6c6f722e" .
            "70726f746f120c636c6172696661692e61706922470a05436f6c6f72120f" .
            "0a077261775f686578180120012809121e0a0377336318022001280b3211" .
            "2e636c6172696661692e6170692e573343120d0a0576616c756518032001" .
            "280222200a03573343120b0a03686578180120012809120c0a046e616d65" .
            "18022001280942245a03617069a2020443414950c202015fca0211436c61" .
            "72696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

