<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/common.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e010a1f70726f746f2f636c6172696661692f6170692f636f6d6d6f6e" .
            "2e70726f746f120c636c6172696661692e617069222f0a0c557365724170" .
            "704944536574120f0a07757365725f6964180120012809120e0a06617070" .
            "5f696418022001280942245a03617069a2020443414950c202015fca0211" .
            "436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

