<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/concept_graph.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class ConceptGraph
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Common::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Utils\Extensions::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7020a2670726f746f2f636c6172696661692f6170692f636f6e636570" .
            "745f67726170682e70726f746f120c636c6172696661692e6170691a2970" .
            "726f746f2f636c6172696661692f6170692f7574696c732f657874656e73" .
            "696f6e732e70726f746f2295010a1b4c697374436f6e6365707452656c61" .
            "74696f6e7352657175657374122f0a0b757365725f6170705f6964180120" .
            "01280b321a2e636c6172696661692e6170692e5573657241707049445365" .
            "7412120a0a636f6e636570745f696418022001280912110a097072656469" .
            "63617465180320012809120c0a047061676518042001280d12100a087065" .
            "725f7061676518052001280d42245a03617069a2020443414950c202015f" .
            "ca0211436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

