<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/embedding.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Embedding
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91010a2270726f746f2f636c6172696661692f6170692f656d62656464" .
            "696e672e70726f746f120c636c6172696661692e61706922370a09456d62" .
            "656464696e6712120a06766563746f721801200328024202100112160a0e" .
            "6e756d5f64696d656e73696f6e7318022001280d421c5a03617069a20204" .
            "43414950ca020d436c6172696661695c47727063620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

