<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/feedback.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Feedback
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa020a2170726f746f2f636c6172696661692f6170692f666565646261" .
            "636b2e70726f746f120c636c6172696661692e617069228a010a0c466565" .
            "646261636b496e666f12130a0b656e645f757365725f6964180120012809" .
            "12120a0a73657373696f6e5f6964180220012809122b0a0a6576656e745f" .
            "7479706518032001280e32172e636c6172696661692e6170692e4576656e" .
            "745479706512110a096f75747075745f696418042001280912110a097365" .
            "617263685f69641805200128092a3c0a094576656e7454797065120d0a09" .
            "756e646566696e6564100012100a0c7365617263685f636c69636b100112" .
            "0e0a0a616e6e6f746174696f6e100242245a03617069a2020443414950c2" .
            "02015fca0211436c6172696661695c496e7465726e616c620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

