<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/focus.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Focus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Utils\Extensions::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91010a1e70726f746f2f636c6172696661692f6170692f666f6375732e" .
            "70726f746f120c636c6172696661692e61706922330a05466f6375731215" .
            "0a0764656e73697479180120012802420480b5180112130a0576616c7565" .
            "180220012802420480b5180142245a03617069a2020443414950c202015f" .
            "ca0211436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

