<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/focus.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Focus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7d0a1e70726f746f2f636c6172696661692f6170692f666f6375732e70" .
            "726f746f120c636c6172696661692e61706922270a05466f637573120f0a" .
            "0764656e73697479180120012802120d0a0576616c756518022001280242" .
            "1c5a03617069a2020443414950ca020d436c6172696661695c4772706362" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

