<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/geo.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Geo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc020a1c70726f746f2f636c6172696661692f6170692f67656f2e7072" .
            "6f746f120c636c6172696661692e617069222f0a0847656f506f696e7412" .
            "110a096c6f6e67697475646518012001280212100a086c61746974756465" .
            "18022001280222270a0847656f4c696d6974120c0a047479706518012001" .
            "2809120d0a0576616c7565180220012802223a0a0d47656f426f78656450" .
            "6f696e7412290a0967656f5f706f696e7418012001280b32162e636c6172" .
            "696661692e6170692e47656f506f696e742289010a0347656f12290a0967" .
            "656f5f706f696e7418012001280b32162e636c6172696661692e6170692e" .
            "47656f506f696e7412290a0967656f5f6c696d697418022001280b32162e" .
            "636c6172696661692e6170692e47656f4c696d6974122c0a0767656f5f62" .
            "6f7818032003280b321b2e636c6172696661692e6170692e47656f426f78" .
            "6564506f696e7442245a03617069a2020443414950c202015fca0211436c" .
            "6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

