<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/geo.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Geo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Utils\Extensions::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e030a1c70726f746f2f636c6172696661692f6170692f67656f2e7072" .
            "6f746f120c636c6172696661692e617069223b0a0847656f506f696e7412" .
            "170a096c6f6e676974756465180120012802420480b5180112160a086c61" .
            "746974756465180220012802420480b51801222d0a0847656f4c696d6974" .
            "120c0a047479706518012001280912130a0576616c756518022001280242" .
            "0480b51801223a0a0d47656f426f786564506f696e7412290a0967656f5f" .
            "706f696e7418012001280b32162e636c6172696661692e6170692e47656f" .
            "506f696e742289010a0347656f12290a0967656f5f706f696e7418012001" .
            "280b32162e636c6172696661692e6170692e47656f506f696e7412290a09" .
            "67656f5f6c696d697418022001280b32162e636c6172696661692e617069" .
            "2e47656f4c696d6974122c0a0767656f5f626f7818032003280b321b2e63" .
            "6c6172696661692e6170692e47656f426f786564506f696e7442245a0361" .
            "7069a2020443414950c202015fca0211436c6172696661695c496e746572" .
            "6e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

