<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/image.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Image
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a1e70726f746f2f636c6172696661692f6170692f696d6167652e" .
            "70726f746f120c636c6172696661692e617069224f0a05496d616765120b" .
            "0a0375726c180120012809120e0a0662617365363418022001280c120c0a" .
            "0463726f70180320032802121b0a13616c6c6f775f6475706c6963617465" .
            "5f75726c18042001280842245a03617069a2020443414950c202015fca02" .
            "11436c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

