<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/output.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Output
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Common::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Data::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Input::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Model::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Status\Status::initOnce();
        \GPBMetadata\Proto\Clarifai\Api\Utils\Extensions::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff040a1f70726f746f2f636c6172696661692f6170692f6f7574707574" .
            "2e70726f746f120c636c6172696661692e6170691a1d70726f746f2f636c" .
            "6172696661692f6170692f646174612e70726f746f1a1e70726f746f2f63" .
            "6c6172696661692f6170692f696e7075742e70726f746f1a1e70726f746f" .
            "2f636c6172696661692f6170692f6d6f64656c2e70726f746f1a2670726f" .
            "746f2f636c6172696661692f6170692f7374617475732f7374617475732e" .
            "70726f746f1a2970726f746f2f636c6172696661692f6170692f7574696c" .
            "732f657874656e73696f6e732e70726f746f1a1f676f6f676c652f70726f" .
            "746f6275662f74696d657374616d702e70726f746f22db010a064f757470" .
            "7574120a0a026964180120012809122b0a0673746174757318022001280b" .
            "321b2e636c6172696661692e6170692e7374617475732e53746174757312" .
            "2e0a0a637265617465645f617418032001280b321a2e676f6f676c652e70" .
            "726f746f6275662e54696d657374616d7012220a056d6f64656c18042001" .
            "280b32132e636c6172696661692e6170692e4d6f64656c12220a05696e70" .
            "757418052001280b32132e636c6172696661692e6170692e496e70757412" .
            "200a046461746118062001280b32122e636c6172696661692e6170692e44" .
            "617461226f0a134d756c74694f7574707574526573706f6e7365122b0a06" .
            "73746174757318012001280b321b2e636c6172696661692e6170692e7374" .
            "617475732e537461747573122b0a076f75747075747318022003280b3214" .
            "2e636c6172696661692e6170692e4f7574707574420480b5180142245a03" .
            "617069a2020443414950c202015fca0211436c6172696661695c496e7465" .
            "726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

