<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/subscription.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Subscription
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Status\Status::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8020a2570726f746f2f636c6172696661692f6170692f737562736372" .
            "697074696f6e2e70726f746f120c636c6172696661692e61706922140a04" .
            "506c616e120c0a046e616d6518012001280922180a164765745375627363" .
            "72697074696f6e5265717565737422500a17506f73745375627363726970" .
            "74696f6e5265717565737412130a0b7369676e75705f636f646518012001" .
            "280912200a04706c616e18022001280b32122e636c6172696661692e6170" .
            "692e506c616e2280010a1a53696e676c65537562736372697074696f6e52" .
            "6573706f6e7365122b0a0673746174757318012001280b321b2e636c6172" .
            "696661692e6170692e7374617475732e53746174757312200a04706c616e" .
            "18022001280b32122e636c6172696661692e6170692e506c616e12130a0b" .
            "7369676e75705f636f646518032001280942245a03617069a20204434149" .
            "50c202015fca0211436c6172696661695c496e7465726e616c620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

