<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/text.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Text
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a700a1d70726f746f2f636c6172696661692f6170692f746578742e7072" .
            "6f746f120c636c6172696661692e61706922130a0454657874120b0a0372" .
            "617718012001280942245a03617069a2020443414950c202015fca021143" .
            "6c6172696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

