<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/usage_interval_type.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class UsageIntervalType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a2c70726f746f2f636c6172696661692f6170692f75736167655f" .
            "696e74657276616c5f747970652e70726f746f120c636c6172696661692e" .
            "6170692a3c0a115573616765496e74657276616c5479706512090a05756e" .
            "646566100012070a03646179100112090a056d6f6e7468100212080a0479" .
            "656172100342245a03617069a2020443414950c202015fca0211436c6172" .
            "696661695c496e7465726e616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

