<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/video.proto

namespace GPBMetadata\Proto\Clarifai\Api;

class Video
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97010a1e70726f746f2f636c6172696661692f6170692f766964656f2e" .
            "70726f746f120c636c6172696661692e61706922410a05566964656f120b" .
            "0a0375726c180120012809120e0a0662617365363418022001280c121b0a" .
            "13616c6c6f775f6475706c69636174655f75726c180420012808421c5a03" .
            "617069a2020443414950ca020d436c6172696661695c4772706362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

