<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/utils/extensions.proto

namespace GPBMetadata\Proto\Clarifai\Api\Utils;

class Extensions
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97010a2970726f746f2f636c6172696661692f6170692f7574696c732f" .
            "657874656e73696f6e732e70726f746f1212636c6172696661692e617069" .
            "2e7574696c731a20676f6f676c652f70726f746f6275662f646573637269" .
            "70746f722e70726f746f422c5a057574696c73a2020443414950c202015f" .
            "ca0217436c6172696661695c496e7465726e616c5c5574696c7362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

