<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/utils/test_proto.proto

namespace GPBMetadata\Proto\Clarifai\Api\Utils;

class TestProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Utils\Extensions::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5010a2970726f746f2f636c6172696661692f6170692f7574696c732f" .
            "746573745f70726f746f2e70726f746f1212636c6172696661692e617069" .
            "2e7574696c73226e0a095465737450726f746f120a0a0269641801200128" .
            "0912280a076d657373616765180220012809421780b518018ab5180f7072" .
            "6f746f732061726520636f6f6c12160a0576616c75651803200128014207" .
            "d5b5180000803f12130a0b696d6167655f627974657318042001280c422c" .
            "5a057574696c73a2020443414950c202015fca0217436c6172696661695c" .
            "496e7465726e616c5c5574696c73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

