<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/utils/pagination/pagination.proto

namespace GPBMetadata\Proto\Clarifai\Utils\Pagination;

class Pagination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a3070726f746f2f636c6172696661692f7574696c732f70616769" .
            "6e6174696f6e2f706167696e6174696f6e2e70726f746f120c636c617269" .
            "6661692e617069222c0a0a506167696e6174696f6e120c0a047061676518" .
            "012001280d12100a087065725f7061676518022001280d42245a03617069" .
            "a2020443414950c202015fca0211436c6172696661695c496e7465726e61" .
            "6c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

