<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/utils/pagination/pagination.proto

namespace GPBMetadata\Proto\Clarifai\Utils\Pagination;

class Pagination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a680a3070726f746f2f636c6172696661692f7574696c732f706167696e" .
            "6174696f6e2f706167696e6174696f6e2e70726f746f222c0a0a50616769" .
            "6e6174696f6e120c0a047061676518012001280d12100a087065725f7061" .
            "676518022001280d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

