<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/utils/pagination/pagination.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Pagination</code>
 */
class Pagination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 page = 1;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>uint32 per_page = 2;</code>
     */
    private $per_page = 0;

    public function __construct() {
        \GPBMetadata\Proto\Clarifai\Utils\Pagination\Pagination::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>uint32 page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 2;</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->per_page = $var;

        return $this;
    }

}

