<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/clarifai/api/status/status.proto

namespace GPBMetadata\Proto\Clarifai\Api\Status;

class Status
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proto\Clarifai\Api\Status\StatusCode::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84030a2670726f746f2f636c6172696661692f6170692f737461747573" .
            "2f7374617475732e70726f746f1213636c6172696661692e6170692e7374" .
            "6174757322cf010a06537461747573122d0a04636f646518012001280e32" .
            "1f2e636c6172696661692e6170692e7374617475732e537461747573436f" .
            "646512130a0b6465736372697074696f6e180220012809120f0a07646574" .
            "61696c7318032001280912130a0b737461636b5f74726163651804200328" .
            "0912190a1170657263656e745f636f6d706c6574656418052001280d1216" .
            "0a0e74696d655f72656d61696e696e6718062001280d120e0a067265715f" .
            "696418072001280912180a10696e7465726e616c5f64657461696c731808" .
            "20012809223b0a0c42617365526573706f6e7365122b0a06737461747573" .
            "18012001280b321b2e636c6172696661692e6170692e7374617475732e53" .
            "7461747573422e5a06737461747573a2020443414950c202015fca021843" .
            "6c6172696661695c496e7465726e616c5c537461747573620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

